name = "grv-link-shrt"
main = "build/worker/shim.mjs"
compatibility_date = "2022-11-28"

[env.dev]
route = "grv-link-shrt.int.pluoi.com/*"

[build]
command = "cargo install -q worker-build && worker-build --release"

[build.upload]
format = "modules"

[[d1_databases]]
binding = "DB"
database_name = "links"
database_id = "8012fb37-862d-4086-aa9e-6b2a1bd43663"
preview_database_id = "8012fb37-862d-4086-aa9e-6b2a1bd43663"

# read more about configuring your Worker via wrangler.toml at:
# https://developers.cloudflare.com/workers/cli-wrangler/configuration
